name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Clean old builds
        run: |
          rm -rf target dist
        shell: bash
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # only needed for build tools

      - name: Install maturin
        run: pip install maturin

      - name: Build wheels
        run: maturin build --release

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: target/wheels/

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: wheels

      - name: Publish to PyPI
        run: |
          pip install twine
          twine upload wheels/**/*.whl -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
